version: '3.3'
services:
  java-api:
  # creation d'un container que l'on nomme java-api à partir du Dockerfile dans ./java/simple-api-main/simple-api
    container_name:
      "java-api"
    build:
      ./java/simple-api-main/simple-api
    networks:
      - "app-network"
    depends_on:
      - "postgres-app"
  
  postgres-app:
  # creation d'un container que l'on nomme postgres-app à partir du Dockerfile dans ./postgres, on utilise un volume pour la persistence des données
    container_name:
      "postgres-app"
    build:
      ./postgres
    networks:
      - "app-network"
    volumes:
      - database_volume:/var/tmp

  front:
    container_name:
      "front"
    build:
      ./devops-front-main
    networks:
      - "app-network"
    ports:
      - "8080:8080"
    depends_on:
      - "java-api"
  
  apache:
  # creation d'un container apache à partir du Dockerfile dans ./apache, on mappe les ports 80:80 pour pouvoir y accèder depuis notre host
    container_name:
      "apache"
    build:
      ./apache
    ports:
      - "80:80"
    networks:
      - "app-network"
    depends_on:
      - "java-api"
      - "front"

#creation du network pour la communication entre les 3 applis
networks:
  app-network:
volumes:
  database_volume: