all:
  vars:
    #on configure notre user
    ansible_user: centos
    #on configure notre chemin vers notre clef privé ssh
    ansible_ssh_private_key_file: .ssh/id_rsa
  children:
    prod:
      hosts: 
        florent.monnet.takima.cloud: