---
# tasks file for roles/launch-database
- name: launch postgres container
  docker_container:
    name: postgres-app
    image: florentmonnet2/postgres-image:1.0
    volumes:
      - /tmp/data
    networks: 
      - name: app-network