#lance le playbook pour tous les hosts(centos@florent.monnet.takima.cloud)
- hosts: all
  gather_facts: false
  #lance en super user
  become: yes
  roles:
  #lance chaque role pour installer docker, créer le réseau, lancer les containers docker
    - install-docker
    - remove-containers
    - create-network
    - launch-database
    - launch-app
    - launch-front
    - launch-proxy