name: Deploy application
on:
  workflow_run:
    workflows: ["Build and push backend"]
    types:
      - completed
    branches: ['production']
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/playbook.yml
          key: ${{secrets.SERVER_RSA}}
          inventory: |
            all:
              vars:
                ansible_user: centos
              children:
                prod:
                  hosts: florent.monnet.takima.cloud