# name: Deploy application
# on:
#   workflow_run:
#     workflows: ["Build & Push Backend"]
#     types:
#       - completed
#     branches: ['main']
#   pull_request:

name: Deploy application
on:
  push:
    branches: ['production']
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set ansible config secrets
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_RSA }}
        run: |
          mkdir ./ansible/.ssh
          echo "$SERVER_SSH_KEY" > ./ansible/.ssh/id_rsa
          chmod 600 ./ansible/.ssh/id_rsa
          ls -al ansible
          
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/playbook.yaml
          key: ${{secrets.SERVER_RSA}}
          inventory: |
            all:
              vars:
                ansible_user: centos
              children:
                prod:
                  hosts: florent.monnet.takima.cloud