# name: Deploy application
# on:
#   workflow_run:
#     workflows: ["Build & Push Backend"]
#     types:
#       - completed
#     branches: ['main']
#   pull_request:

name: Deploy application
on:
  push:
    branches: ['production']
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set ansible config secrets
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_RSA }}
        run: |
          mkdir ./ansible/.ssh
          echo "$SERVER_SSH_KEY" > ./ansible/.ssh/id_rsa
          chmod 600 ./ansible/.ssh/id_rsa
          
      - name: run exporters playbook
        run: |
          cd ansible
          ansible-playbook -i ./inventories/setup.yml ./playbook.yml